version: '3'
services:
  python-app:
    image: python:3.9
    volumes:
      - ./python_app:/app
    working_dir: /app
    command: python hello.py
    environment:
      - JAVA_APP_HOST=java-app

  java-app:
    image: openjdk:21
    volumes:
      - ./java_app:/app
    working_dir: /app
    command: java HelloWorld
    depends_on:
      - python-app

